@startuml
'https://plantuml.com/class-diagram

skinparam classAttributeIconSize 0

package parser {
    class HabitCommandParser {
    }

    class Parser {
    }
}

package command {
    interface "<<interface>>\nCommand" as Command {
               + execute(): void
               + isExit(): boolean
    }

    class AddHabitCommand implements Command {
    }

    class DeleteHabitCommand implements Command {
    }

    class ListHabitsCommand implements Command {
    }

    class SetPriorityCommand implements Command {
    }

    class SortHabitsCommand implements Command {
    }

    class UpdateHabitCountCommand implements Command {
    }

    class HabitHelpCommand implements Command {
    }
}

Package habit {
    class HabitTracker {
        - habitList: ArrayList<habit>

        + HabitTracker()
        + getNumberOfHabits(): int
        + addHabit(newHabit: Habit): void
        + listHabits(): void
        + isValidHabitID(habitID: int): boolean
        + updateHabitCount(habitID: int, updatedCount: String): void
        + deleteHabit(habitID: int): void
        + setPriorityLevel(habitID: int, priority String): void
        + sortHabits(): void
        + clearHabitList(): void
    }

    class Habit {
        - description: String
        - habitCount: int
        - priority: Priority

        + Habit(description: String)
        + Habit(description: String, habitCount: int, priority: Priority)
        + getDescription(): String
        + getHabitCount(): int
        + getPriority(): Priority
        + updateCount(updatedCount: String): int
        + setPriority(priority: String): void
    }

    enum Priority {
      HIGH
      MED
      LOW
    }
}

Package storage {
    class Storage {
    }

    class HabitTrackerStorage {
        + saveHabitListToFile(habitList: ArrayList<Habit>): void
        + loadHabitListFromFile(): ArrayList<Habit>
    }
}

class Ui {
}

HabitTracker *-- "*" Habit : contains
Habit *-- "1" Priority : contains

HabitTracker --> HabitTrackerStorage : uses >
HabitTrackerStorage --> Storage : uses >
HabitTracker --> Ui : uses >

Parser ..> HabitCommandParser : creates >
HabitCommandParser .DOWN.> AddHabitCommand : creates >
HabitCommandParser .DOWN.> DeleteHabitCommand : creates >
HabitCommandParser .DOWN.> ListHabitsCommand : creates >
HabitCommandParser .DOWN.> SetPriorityCommand : creates >
HabitCommandParser .DOWN.> SortHabitsCommand : creates >
HabitCommandParser .DOWN.> UpdateHabitCountCommand : creates >
HabitCommandParser .DOWN.> HabitHelpCommand : creates >

AddHabitCommand --> HabitTracker : uses >
DeleteHabitCommand --> HabitTracker : uses >
ListHabitsCommand --> HabitTracker : uses >
SetPriorityCommand --> HabitTracker : uses >
SortHabitsCommand --> HabitTracker : uses >
UpdateHabitCountCommand --> HabitTracker : uses >



@enduml

