@startuml
!include style.puml
skinparam ArrowFontStyle plain

Actor User as user USER_COLOR
Participant ":UI" as ui UI_COLOR
Participant ":StockPal" as stockpal STOCKPAL_COLOR
Participant ":Parser" as parser PARSER_COLOR
Participant ":DeleteCommand" as command COMMANDS_COLOR
Participant ":Storage" as storage STORAGE_COLOR

activate stockpal STOCKPAL_COLOR

user -[USER_COLOR]> ui : "delete 2"
activate ui UI_COLOR

ui -[UI_COLOR]> stockpal : "delete 2"

stockpal -[STOCKPAL_COLOR]> parser : parseCommand("delete 2")
activate parser PARSER_COLOR

create command
parser -[PARSER_COLOR]> command : new DeleteCommand(pid)
activate command COMMANDS_COLOR
parser <--[COMMANDS_COLOR] command
deactivate command

parser --[PARSER_COLOR]> stockpal : command : DeleteCommand
deactivate parser

stockpal -[STOCKPAL_COLOR]> command : execute()
activate command COMMANDS_COLOR

note over command
    Delete product from productList
end note

command -[COMMANDS_COLOR]> ui : printDeleteSuccessMessage()
user <-[UI_COLOR] ui : "Product has been deleted."
ui [UI_COLOR]--> command
stockpal <--[COMMANDS_COLOR] command
deactivate command

stockpal -[STOCKPAL_COLOR]> storage : saveData(productList)
activate storage STORAGE_COLOR

storage -[STORAGE_COLOR]> storage : Save to file
activate storage STORAGE_COLOR
storage --[STORAGE_COLOR]> storage
deactivate storage

storage --[STORAGE_COLOR]> stockpal
deactivate storage

destroy command
@enduml