@startuml
!include style.puml
skinparam ArrowFontStyle plain

Actor User as user USER_COLOR
Participant ":UI" as ui UI_COLOR
Participant ":StockPal" as stockpal STOCKPAL_COLOR
Participant ":Parser" as parser PARSER_COLOR
Participant ":command:InflowCommand" as commands COMMANDS_COLOR
Participant ":data" as data DATA_COLOR

activate stockpal STOCKPAL_COLOR

user -[USER_COLOR]> ui : "inflow 2 a/10"
activate ui UI_COLOR

ui -[UI_COLOR]> stockpal : "inflow 2 a/10"

stockpal -[PARSER_COLOR]> parser : parseCommand("inflow 2 a/10")
activate parser PARSER_COLOR

create commands
parser -[PARSER_COLOR]> commands : new InflowCommand(pid, increaseBy)
activate commands COMMANDS_COLOR
commands --[COMMANDS_COLOR]> parser : commands

parser --[PARSER_COLOR]> stockpal : commands
deactivate parser

stockpal -[STOCKPAL_COLOR]> commands : execute(InflowCommand(pid, increaseBy))
commands -[COMMANDS_COLOR]> data : increaseAmountCaller(pid, increaseBy)
activate data DATA_COLOR

data -[DATA_COLOR]> data : updateQuantity(pid, increaseBy, "increase")
activate data DATA_COLOR
data --[DATA_COLOR]> data
deactivate data

data -[DATA_COLOR]> data : updateIncreaseQuantity(quantityClass, increaseBy)
activate data DATA_COLOR
data --[DATA_COLOR]> data
deactivate data

data --[DATA_COLOR]> commands

commands -[COMMANDS_COLOR]> ui

deactivate commands
deactivate data

ui --[UI_COLOR]> user : "Quantity updated. Quantity: 20"

@enduml
