@startuml
'https://plantuml.com/sequence-diagram

autonumber
actor User
participant UI << static >>
activate Logic
participant GeneralInputParser
participant SummariseParser << static >>
participant Dashboard order 30
participant ExpenseManager order 31
participant GeneralFileManager order 32
Logic -> UI ++ : getUserInput()

User -> UI : "summarise"
UI --> Logic : "summarise"

Logic -> GeneralInputParser ++ : getCommandFromUserInput("summarise")
GeneralInputParser -> SummariseParser ++ : parseInput("summarise")
SummariseParser -> SummariseCommand ** : new SummariseCommand(...)
activate SummariseCommand

SummariseParser --> GeneralInputParser -- : commandToExecute
GeneralInputParser --> Logic -- : command
Logic -> SummariseCommand -- : execute(...)
SummariseCommand -> Dashboard ++ : getExpenseManager()
Dashboard --> SummariseCommand -- : ExpenseManager
SummariseCommand -> ExpenseManager ++ : summariseExpenses(...)
ExpenseManager --> SummariseCommand -- : summary
SummariseCommand -> UI -- : prettyPrint(summary)
UI --> User -- : summary

activate Logic
Logic -> Dashboard ++ : getExpenseManager
Dashboard --> Logic -- : ExpenseManager
Logic -> ExpenseManager ++ : getExpensesStringRepresentation
ExpenseManager --> Logic -- : expenseListToSave
Logic -> Dashboard ++ : getGeneralFileManager
Dashboard --> Logic -- : GeneralFileManager
Logic -> GeneralFileManager ++ : save(expenseListToSave)


@enduml