@startuml
autoactivate on
participant ": Timetable" as timetable
participant "courses: ArrayList<ArrayList<Course>>" as courses
participant ": Grade" as grade

[-> timetable : addGrade()
loop until current course matches target course code or end of list reached
    timetable -> courses : check course code
    timetable <-- courses
    deactivate courses
end

opt target course code found
    timetable -> courses : add grade to the course
    courses -> grade : set the grade
    courses <-- grade
    timetable <-- courses
    deactivate courses
    deactivate grade
end

[<-- timetable : whether target course code was found
deactivate timetable
@enduml